### ISSUE TITLE
Komponenten auf verschiedene Repositories verteilen

### ISSUE THREAD

**Issue by alfredbez** [ioly/ioly#43]
Warum liegen die verschiedenen Komponenten in einem Repository auf verschiedenen Branches?

Wäre es nicht sinnvoller die Komponenten (Core, Connector usw) in verschiedenen Repositories aufzuteilen?

**Comment by tabsl** [comment]
wir hatten uns das am anfang überlegt. die gründe wieso wir uns dagegen entschieden haben:
- wir wollten alle issues auf einen blick haben (wären sonst verteilt)
- alle PRs laufen ins gleiche repo (auch wenn unterschiedliche branches)
- statistik

**Comment by alfredbez** [comment]
Alle Issues auf einen Blick: `is:open is:issue user:ioly`
Alle PR's auf einen Blick: `is:open is:pr user:ioly`
jeweils oben ins Suchfeld eingeben

![just-sayin](https://cloud.githubusercontent.com/assets/1001186/5897198/7489d5c8-a541-11e4-98ec-a26eadce7a17.jpg)

**Comment by proudcommerce** [comment]
nice, danke für die info.
