### ISSUE TITLE
Support of private Repositories

### ISSUE THREAD

**Issue by job963** [ioly/ioly#56]
If the repository is private, the cookbook data aren't sufficient.

* there should be a field to mark the module as private
* the download process should ask for the login credentials

**Comment by smxsm** [comment]
There is now basic support for commercial / private modules, see https://github.com/ioly/ioly/wiki/Writing-a-recipe#commercial-modules - feel free to test and give feedback :)

**Comment by proudcommerce** [comment]
featured with https://github.com/ioly/ioly/commit/7496b397f1f003d7ecb45079111b5acb14daa42a

**Comment by smxsm** [comment]
supported via commercial modules now
