### ISSUE TITLE
wrong displayed module list after update

### ISSUE THREAD

**Issue by a4p-ASD** [ioly/ioly#61]
I have updated ioly (core + oxid-connector) from 1.6.3 to 1.7.2 with the update buttons from ioly.
After that (and versions >1.6.3) the module list looks like this:

![image](https://cloud.githubusercontent.com/assets/10755387/14521392/6170c078-0229-11e6-9082-e03f411d18df.png)

Only version 1.6.3 works...
No new Exceptions or errors occur, when i open ioly.

The only errors (while updating ?):
PHP Warning:  array_combine() expects parameter 1 to be array, null given in /var/www/vhosts/drucksachencloud-stage.de/modules/ioly/ioly/ioly.php on line 274, referer: 
PHP Warning:  array_map(): Argument #2 should be an array in /var/www/vhosts/drucksachencloud-stage.de/modules/ioly/ioly/ioly.php on line 274, referer: 

Any suggestion?

**Comment by smxsm** [comment]
Looks like the required libs were not found... can you try to activate the "auto-update" checkbox in the module settings so that the libs should be downloaded again?

**Comment by a4p-ASD** [comment]
no, sorry - did not work...

**Comment by a4p-ASD** [comment]
completely new install of ioly-connector worked!
Can i import the status of the installed modules from the old version?

**Comment by smxsm** [comment]
hm, that's weird :(
Yes, you should be able to copy the old .recipes.db and .digest.db files to get the installed status etc. back

**Comment by a4p-ASD** [comment]
I see a difference between the old and the current ioly version:
in the shop root folder i had another ioly-folder (containing libs-folder). This is no more needed?

I tried it with the old *.db-files - ioly is still working on it ... (loading; message "undefined (Error undefined)" was displayed; loading)

**Comment by a4p-ASD** [comment]
Maybe my custom cookbooks are the problem?!

**Comment by smxsm** [comment]
No, custom cookbooks shouldn't matter, I think it was a problem with the root "ioly" folder - we've moved this folder into the module dir because of access rights problems in the shop root. So the external "/ioly" folder is not necessary anymore and can be deleted.

**Comment by a4p-ASD** [comment]
OK, thank you!

Now it works! I removed the checkbox for checking if module is activated - now the install-states are there again.
If i activate this function - ioly loads to death... (166 receipes) :-) !?

**Comment by a4p-ASD** [comment]
No, sorry - maybe it stopped working because of an javascript error:
![image](https://cloud.githubusercontent.com/assets/10755387/14525718/14fce396-023f-11e6-8f2a-688a9709e3c4.png)

**Comment by proudcommerce** [comment]
jquery is loaded?

**Comment by a4p-ASD** [comment]
No, doesn´t look so!

Can´t find it in the frames source code:
[frame_source.txt](https://github.com/ioly/ioly/files/220571/frame_source.txt)

(url: http://drucksachencloud-stage.de/admin/index.php?force_admin_sid=00s....e1i2jip2&stoken=106B...C&cl=ioly_main##iolyerrors)

**Comment by a4p-ASD** [comment]
added "<script src="[{$oViewConf->getResourceUrl('js/libs/jquery.min.js')}]"></script>" to file \modules\ioly\ioly\blocks\admin_headitem_incjs.tpl as first js-include.

Auto-update is deactivated.

No difference - same js errors...

How long should it take to check all (?) modules?

**Comment by smxsm** [comment]
Hm, it should only check the installed modules... and only per page (default max. 10)... how many modules do you have installed with ioly?

Concerning the "libs" directory in ioly when updating from an old version of the connector ... if possible, it should be moved from /ioly/libs/... to /modules/ioly/ioly/libs/.... Or, if it was deleted, you can re-install the libs with

```
cd /var/www/myshop.de/modules/ioly/ioly
export IOLY_SYSTEM_VERSION=5.2
export IOLY_SYSTEM_BASE=/var/www/myshop.de/
php ioly.php install ioly/oxid-connector-js-libs 1.0.0
```

The problem is that if you just delete the "/ioly/libs" folder, ioly core still thinks it is installed and will never re-install the JS libs again, so you have to re-install the libs as posted above in this case. Or, like you did, re-install the complete ioly OXID Connector module.

**Comment by a4p-ASD** [comment]
I test the setting "check installed modules.." in a new shop with and without my cookbooks. Maybe then i find the problem...

**Comment by a4p-ASD** [comment]
I´ve setup a new shop, installed and updated ioly, added custom cookbooks, activated all module options - and everything works...
And no javascript errors here. I think my own json files caused the error.

Thanks - can be closed
